### ISSUE TITLE
Any plans to implement live filtering?

### ISSUE THREAD

**Issue by alejandrogallo** [huijunchen9260/shellect#1]
Almost all tools like this support live filtering, right now here
one has to press `/`, enter a text, and press `enter` to select.
Wouldn't it be better not to have to press `/` and to see a live filtering of the options as one types in the text?

**Comment by alejandrogallo** [comment]
This is not super important, maybe it could be a flag where you can have this behaviour, `-l` or so

**Comment by huijunchen9260** [comment]
Implementing this would be a milestone.

In dylanarps' [cmd_line](https://github.com/dylanaraps/fff/blob/master/fff#L624-L736) function in project [fff](https://github.com/dylanaraps/fff), he implemented live filtering using `read -rsn1`. POSIX `read` only has `-r` option, and `-n 1` is the part which process every key that user press.

At the time I saw this issue, I have an idea on how to implement live filtering in POSIX standard. Not sure whether it would work, but I'll give it a try. 
I can replace `read -n 1`'s action as `dd ibs=1 count=1`, as in my [key](https://github.com/huijunchen9260/shmenu/blob/main/shmenu#L377) function. Then at each time user press a key, the script can process it once using [search](https://github.com/huijunchen9260/shmenu/blob/main/shmenu#L324) function. 

Thank you for raising this up. Hope this would work!

**Comment by huijunchen9260** [comment]
I've created a new branch [live-search](https://github.com/huijunchen9260/shmenu/tree/live-search). This is like a prototype rather than a good way to do it.

Somehow `stty icanon` will allow the typing in the last line to appear, but not live search. Disable it by `stty -icanon` will suppress the bottom prompt but allow for live search. If you are interested in this idea, would you mind give me some idea on how to accomplish both?

Thank you!

**Comment by huijunchen9260** [comment]
Implemented by [a147409](https://github.com/huijunchen9260/shellect/commit/a1474097984d5ef751cb2ac5cc89f3dff376c0ba)
