### ISSUE TITLE
Enable selecting multiple option with keybind

### ISSUE THREAD

**Issue by L1so** [huijunchen9260/shellect#2]
Hello, great work with the script ! I used it and it's really good.

I have an idea (possibly feature request), can you create a new keybind to toggle multiple selection, so after the user is done selecting and pressing <kbd>Enter</kbd>. It will output newline separated selection to stdout.

Thanks !

**Comment by huijunchen9260** [comment]
Hi L1so:

I would say it might be hard to implement since the POSIX shell only contains 1 implicit array, which is the array of argument `$@`. If you say that I can use a variable to store the selected item, then I also need to consider the user de-selecting items in random order.  That being said, my [fm.awk](https://github.com/huijunchen9260/fm.awk) project actually allows users to select and de-select items in random order since awk enables me to have multiple arrays. 

What do you think? Do you have any ideas on how to achieve this in the POSIX shell?

HJ

**Comment by L1so** [comment]
How about using a temporary file to store checked items, if unchecked remove the checked items from the temporary file, but put a delimiter between each value.

Later for retrieval, do a `while read IFS=(delimiter)` to print each value. It is what i use on my project https://github.com/L1so/benchy/blob/main/benchy#L776 to deal with this problem. My project is also shell independent.

Do you have dedicated selection menu like shellect but written in awk ? fm.awk is a file manager, though I only need the selection part. And I think awk guaranteed to work in most Linux (shell) right ?

Thanks !

**Comment by huijunchen9260** [comment]
Sadly I don't have such a selection menu written in awk. I thought of doing it, but I realized what I want cannot be achieved by a single selection menu, so I give up and simply make an interface for my file manager.

What do you think should be inside a selection menu? One of the reason I wrote shellect is because fzf cannot accept delimiter at that time. But now a brief search in the manual tells me that the `-d` option in fzf can allow you to have different delimiter than `\n` (am I right?). Could shellect beat fzf? Probably not. POSIX shell is still a pretty limited language in terms of both usage and efficiency. You are more than welcome to contribute, I can also think of a better way to achieve multiple selection if that is possible.

**Comment by L1so** [comment]
That would be amazing, I hope you can implement that :smiley:

**Comment by huijunchen9260** [comment]
Are you trying to answer my questions? Or make any contributions?

**Comment by L1so** [comment]
> You are more than welcome to contribute, I can also think of a better way to achieve multiple selection if that is possible.

I simply responded to this bit here, if it's not possible-- its fine, you can close this issue.

**Comment by schmurtzm** [comment]
Just in case @L1so  I've made a kind of [easy checkbox management whith shellect here](https://github.com/OnionUI/Onion/blob/63636a574594839c15e223fb472d332e049588e6/static/build/.tmp_update/script/scraper/menu.sh#L180).
